"""Shared layout primitives."""
from __future__ import annotations

from pptx.enum.shapes import MSO_SHAPE
from pptx.enum.text import PP_ALIGN
from pptx.util import Inches, Pt

from pptskill.fonts import style_run
from pptskill.theme import Theme

SLIDE_W = Inches(13.333)
SLIDE_H = Inches(7.5)


def blank_slide(prs):
    return prs.slides.add_slide(prs.slide_layouts[6])


def add_rect(slide, x, y, w, h, fill=None, line=None, radius=False):
    shape = slide.shapes.add_shape(
        MSO_SHAPE.ROUNDED_RECTANGLE if radius else MSO_SHAPE.RECTANGLE, x, y, w, h
    )
    if fill is None:
        shape.fill.background()
    else:
        shape.fill.solid()
        shape.fill.fore_color.rgb = fill
    if line is None:
        shape.line.fill.background()
    else:
        shape.line.color.rgb = line
        shape.line.width = Pt(1)
    if radius:
        try:
            shape.adjustments[0] = 0.08
        except Exception:
            pass
    return shape


def add_bg(slide, color):
    bg = add_rect(slide, 0, 0, SLIDE_W, SLIDE_H, fill=color)
    spTree = bg._element.getparent()
    spTree.remove(bg._element)
    spTree.insert(2, bg._element)
    return bg


def add_text(slide, x, y, w, h, text, theme: Theme, *, size=16, bold=False, color=None, align=PP_ALIGN.LEFT, dark=False):
    box = slide.shapes.add_textbox(x, y, w, h)
    tf = box.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    p.alignment = align
    p.text = text
    ink = theme.ink if dark else theme.ink_on_light
    style_run(
        p.runs[0],
        size=size,
        bold=bold,
        color=color if color is not None else ink,
        font_cjk=theme.font_cjk,
        font_latin=theme.font_latin,
    )
    return box


def add_title_bar(slide, title, theme: Theme, *, subtitle=None, dark=False):
    title_color = theme.ink if dark else theme.ink_on_light
    sub_color = theme.muted if dark else theme.muted_on_light
    add_text(slide, Inches(0.7), Inches(0.42), Inches(11.5), Inches(0.55),
             title, theme, size=28, bold=True, color=title_color, dark=dark)
    add_rect(slide, Inches(0.7), Inches(1.05), Inches(1.1), Inches(0.06), fill=theme.accent)
    if subtitle:
        add_text(slide, Inches(0.7), Inches(1.18), Inches(11.5), Inches(0.35),
                 subtitle, theme, size=13, color=sub_color, dark=dark)


def add_footer(slide, page, total, theme: Theme, *, dark=False):
    color = theme.muted if dark else theme.muted_on_light
    add_text(slide, Inches(0.7), Inches(7.05), Inches(6), Inches(0.3),
             "Generated by pptskill", theme, size=10, color=color, dark=dark)
    add_text(slide, Inches(11.5), Inches(7.05), Inches(1.2), Inches(0.3),
             f"{page} / {total}", theme, size=10, color=color, align=PP_ALIGN.RIGHT, dark=dark)


def add_stat_card(slide, x, y, w, h, number, label, theme: Theme):
    add_rect(slide, x, y, w, h, fill=theme.card_on_light, line=theme.border_on_light, radius=True)
    add_rect(slide, x, y, Inches(0.08), h, fill=theme.accent)
    add_text(slide, x + Inches(0.25), y + Inches(0.2), w - Inches(0.4), Inches(0.7),
             number, theme, size=28, bold=True, color=theme.ink_on_light)
    add_text(slide, x + Inches(0.25), y + Inches(0.95), w - Inches(0.4), h - Inches(1.05),
             label, theme, size=13, color=theme.muted_on_light)


def set_notes(slide, text: str) -> None:
    if not text:
        return
    slide.notes_slide.notes_text_frame.text = text
